CREATE DATABASE IF NOT EXISTS war_game;
USE war_game;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS current_games (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL UNIQUE,
  player_deck JSON NOT NULL,
  computer_deck JSON NOT NULL,
  pot JSON NOT NULL,
  rounds INT NOT NULL DEFAULT 0,
  last_player_card JSON NULL,
  last_computer_card JSON NULL,
  last_result VARCHAR(30) NOT NULL DEFAULT 'ready',
  is_finished TINYINT(1) NOT NULL DEFAULT 0,
  winner VARCHAR(20) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS game_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  rounds INT NOT NULL,
  result VARCHAR(10) NOT NULL,
  finished_at DATETIME NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
